export const orderVolumes = [
  { value: "1", label: "+10" },
  { value: "2", label: "+30" },
  { value: "3", label: "+100" },
  { value: "4", label: "+200" },
];

export const businessesType = [
  { value: "1", label: "Clothes Stores" },
  { value: "2", label: "Grocery Stores & Supermarkets" },
  { value: "3", label: "Restaurants" },
  { value: "4", label: "Fast food" },
  { value: "5", label: "Cafes & Coffee Shops" },
  { value: "6", label: "Pharmacies" },
  { value: "7", label: "Event Planners" },
  { value: "8", label: "Other" },
];

export const softwareTypes = [
  { value: "Agroalimentaire", label: "Agroalimentaire" },
  { value: "Agriculture et élevage", label: "Agriculture et élevage" },
  { value: "Apiculture", label: "Apiculture" },
  { value: "Aquaculture et pêche", label: "Aquaculture et pêche" },
  { value: "Articles de sport et loisirs", label: "Articles de sport et loisirs" },
  { value: "Artisanat traditionnel", label: "Artisanat traditionnel" },
  { value: "Automobile et pièces détachées", label: "Automobile et pièces détachées" },
  { value: "Bâtiment et travaux publics (BTP)", label: "Bâtiment et travaux publics (BTP)" },
  { value: "Bois et menuiserie", label: "Bois et menuiserie" },
  { value: "Bijouterie et horlogerie", label: "Bijouterie et horlogerie" },
  { value: "Bureautique et papeterie", label: "Bureautique et papeterie" },
  { value: "Céramique et porcelaine", label: "Céramique et porcelaine" },
  { value: "Chaussures et maroquinerie", label: "Chaussures et maroquinerie" },
  { value: "Chimie et produits chimiques", label: "Chimie et produits chimiques" },
  { value: "Climatisation et froid industriel", label: "Climatisation et froid industriel" },
  { value: "Commerce général", label: "Commerce général" },
  { value: "Communication et publicité", label: "Communication et publicité" },
  { value: "Conception graphique et impression", label: "Conception graphique et impression" },
  { value: "Construction métallique", label: "Construction métallique" },
  { value: "Décoration intérieure", label: "Décoration intérieure" },
  { value: "Dérivés pétroliers et lubrifiants", label: "Dérivés pétroliers et lubrifiants" },
  { value: "Distribution d’eau / hydraulique", label: "Distribution d’eau / hydraulique" },
  { value: "Électricité (installation, matériel…)", label: "Électricité (installation, matériel…)" },
  { value: "Électronique et électroménager", label: "Électronique et électroménager" },
  { value: "Emballage et packaging", label: "Emballage et packaging" },
  { value: "Énergies renouvelables", label: "Énergies renouvelables" },
  { value: "Enseignement et formation", label: "Enseignement et formation" },
  { value: "Équipements agricoles", label: "Équipements agricoles" },
  { value: "Équipements industriels", label: "Équipements industriels" },
  { value: "Équipements médicaux", label: "Équipements médicaux" },
  { value: "Équipements de sécurité", label: "Équipements de sécurité" },
  { value: "Événementiel", label: "Événementiel" },
  { value: "Fabrication de meubles", label: "Fabrication de meubles" },
  { value: "Fournitures médicales et paramédicales", label: "Fournitures médicales" },
  { value: "Génie civil", label: "Génie civil" },
  { value: "Hôtellerie et restauration", label: "Hôtellerie et restauration" },
  { value: "Hygiène et nettoyage", label: "Hygiène et nettoyage" },
  { value: "Imprimerie", label: "Imprimerie" },
  { value: "Import – export", label: "Import – export" },
  { value: "Informatique (vente, services, développement)", label: "Informatique" },
  { value: "Installations sanitaires / plomberie", label: "Installations sanitaires / plomberie" },
  { value: "Isolation thermique et acoustique", label: "Isolation thermique et acoustique" },
  { value: "Jardinage et espaces verts", label: "Jardinage et espaces verts" },
  { value: "Maintenance industrielle", label: "Maintenance industrielle" },
  { value: "Manutention et levage", label: "Manutention et levage" },
  { value: "Matériaux de construction", label: "Matériaux de construction" },
  { value: "Matériel scolaire", label: "Matériel scolaire" },
  { value: "Mécanique générale", label: "Mécanique générale" },
  { value: "Métallerie", label: "Métallerie" },
  { value: "Nettoyage industriel", label: "Nettoyage industriel" },
  { value: "Parfumerie et cosmétique", label: "Parfumerie et cosmétique" },
  { value: "Peinture et revêtement", label: "Peinture et revêtement" },
  { value: "Pharmaceutique", label: "Pharmaceutique" },
  { value: "Photographie et audiovisuel", label: "Photographie et audiovisuel" },
  { value: "Produits d’entretien", label: "Produits d’entretien" },
  { value: "Produits laitiers", label: "Produits laitiers" },
  { value: "Recyclage et gestion des déchets", label: "Recyclage et gestion des déchets" },
  { value: "Santé animale", label: "Santé animale" },
  { value: "Services juridiques et comptables", label: "Services juridiques et comptables" },
  { value: "Solaire / photovoltaïque", label: "Solaire / photovoltaïque" },
  { value: "Télécommunications", label: "Télécommunications" },
  { value: "Textile, vêtements, linge de maison", label: "Textile, vêtements, linge de maison" },
  { value: "Tôlerie", label: "Tôlerie" },
  { value: "Transport et logistique", label: "Transport et logistique" },
  { value: "Travaux de voirie", label: "Travaux de voirie" },
  { value: "Verrerie", label: "Verrerie" }
];

export const usersNumber = [
  { value: "1", label: "1 | Adrar" },
  { value: "2", label: "2 | Chlef" },
  { value: "3", label: "3 | Laghouat" },
  { value: "4", label: "4 | Oum El Bouaghi" },
  { value: "5", label: "5 | Batna" },
  { value: "6", label: "6 | Béjaïa" },
  { value: "7", label: "7 | Biskra" },
  { value: "8", label: "8 | Béchar" },
  { value: "9", label: "9 | Blida" },
  { value: "10", label: "10 | Bouira" },
  { value: "11", label: "11 | Tamanrasset" },
  { value: "12", label: "12 | Tébessa" },
  { value: "13", label: "13 | Tlemcen" },
  { value: "14", label: "14 | Tiaret" },
  { value: "15", label: "15 | Tizi Ouzou" },
  { value: "16", label: "16 | Alger" },
  { value: "17", label: "17 | Djelfa" },
  { value: "18", label: "18 | Jijel" },
  { value: "19", label: "19 | Sétif" },
  { value: "20", label: "20 | Saïda" },
  { value: "21", label: "21 | Skikda" },
  { value: "22", label: "22 | Sidi Bel Abbès" },
  { value: "23", label: "23 | Annaba" },
  { value: "24", label: "24 | Guelma" },
  { value: "25", label: "25 | Constantine" },
  { value: "26", label: "26 | Médéa" },
  { value: "27", label: "27 | Mostaganem" },
  { value: "28", label: "28 | M’Sila" },
  { value: "29", label: "29 | Mascara" },
  { value: "30", label: "30 | Ouargla" },
  { value: "31", label: "31 | Oran" },
  { value: "32", label: "32 | El Bayadh" },
  { value: "33", label: "33 | Illizi" },
  { value: "34", label: "34 | Bordj Bou Arréridj" },
  { value: "35", label: "35 | Boumerdès" },
  { value: "36", label: "36 | El Tarf" },
  { value: "37", label: "37 | Tindouf" },
  { value: "38", label: "38 | Tissemsilt" },
  { value: "39", label: "39 | El Oued" },
  { value: "40", label: "40 | Khenchela" },
  { value: "41", label: "41 | Souk Ahras" },
  { value: "42", label: "42 | Tipaza" },
  { value: "43", label: "43 | Mila" },
  { value: "44", label: "44 | Aïn Defla" },
  { value: "45", label: "45 | Naâma" },
  { value: "46", label: "46 | Aïn Témouchent" },
  { value: "47", label: "47 | Ghardaïa" },
  { value: "48", label: "48 | Relizane" },
  { value: "49", label: "49 | Timimoun" },
  { value: "50", label: "50 | Bordj Badji Mokhtar" },
  { value: "51", label: "51 | Ouled Djellal" },
  { value: "52", label: "52 | Béni Abbès" },
  { value: "53", label: "53 | In Salah" },
  { value: "54", label: "54 | In Guezzam" },
  { value: "55", label: "55 | Touggourt" },
  { value: "56", label: "56 | Djanet" },
  { value: "57", label: "57 | El M'Ghair" },
  { value: "58", label: "58 | El Meniaa" }
];

export const softwareLanguages = [
  { value: "1", label: "Arabe" },
  { value: "2", label: "French" },
  { value: "3", label: "English" },
  { value: "4", label: "Other" },
];
